// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.js";
import * as A11yTs from "./bindings/a11y.ts";

function checkAccessibility(prim0, prim1) {
  return A11yTs.checkAccessibility(prim0, prim1);
}

async function check(html, url) {
  return await A11yTs.checkAccessibility(html, url);
}

function levelToString(level) {
  switch (level) {
    case "A" :
        return "A";
    case "AA" :
        return "AA";
    case "AAA" :
        return "AAA";
    
  }
}

function levelFromString(str) {
  var match = str.toUpperCase();
  switch (match) {
    case "A" :
        return "A";
    case "AA" :
        return "AA";
    case "AAA" :
        return "AAA";
    default:
      return ;
  }
}

function filterByLevel(issues, level) {
  return issues.filter(function (issue) {
              var match = issue.level;
              switch (match) {
                case "A" :
                    return true;
                case "AA" :
                    switch (level) {
                      case "A" :
                          return false;
                      case "AA" :
                      case "AAA" :
                          return true;
                      
                    }
                case "AAA" :
                    switch (level) {
                      case "A" :
                      case "AA" :
                          return false;
                      case "AAA" :
                          return true;
                      
                    }
                
              }
            });
}

function filterByCritical(issues) {
  return issues.filter(function (issue) {
              if (issue.impact === "critical") {
                return true;
              } else {
                return issue.impact === "serious";
              }
            });
}

function calculateScore(result) {
  var criticalViolations = result.violations.filter(function (v) {
        return v.impact === "critical";
      }).length;
  var seriousViolations = result.violations.filter(function (v) {
        return v.impact === "serious";
      }).length;
  var moderateViolations = result.violations.filter(function (v) {
        return v.impact === "moderate";
      }).length;
  var minorViolations = result.violations.filter(function (v) {
        return v.impact === "minor";
      }).length;
  var totalChecks = (result.passes + result.violations.length | 0) + result.incomplete | 0;
  if (totalChecks === 0.0) {
    return 100.0;
  }
  var deductions = criticalViolations * 10.0 + seriousViolations * 5.0 + moderateViolations * 2.0 + minorViolations * 0.5;
  var score = 100.0 - deductions;
  if (score < 0.0) {
    return 0.0;
  } else {
    return score;
  }
}

function groupByRule(issues) {
  var grouped = {};
  issues.forEach(function (issue) {
        var existing = Core__Option.getOr(grouped[issue.rule], []);
        existing.push(issue);
        grouped[issue.rule] = existing;
      });
  return grouped;
}

function getSummary(result) {
  var criticalCount = filterByCritical(result.violations).length;
  var score = calculateScore(result);
  return "Accessibility Score: " + score.toString() + "/100 | " + ("Violations: " + result.violations.length.toString() + " ") + ("(" + criticalCount.toString() + " critical) | ") + ("WCAG Level: " + levelToString(result.wcagLevel));
}

export {
  checkAccessibility ,
  check ,
  levelToString ,
  levelFromString ,
  filterByLevel ,
  filterByCritical ,
  calculateScore ,
  groupByRule ,
  getSummary ,
}
/* ./bindings/a11y.ts Not a pure module */
