// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SEO from "./SEO.js";
import * as Config from "./Config.js";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Report from "./Report.js";
import * as Fetcher from "./Fetcher.js";
import * as UrlParser from "./UrlParser.js";
import * as LinkChecker from "./LinkChecker.js";
import * as $$Performance from "./Performance.js";
import * as Core__Option from "@rescript/core/src/Core__Option.js";
import * as Accessibility from "./Accessibility.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

var defaultOptions = {
  config: Config.default,
  checkLinks: true,
  checkAccessibility: true,
  checkPerformance: true,
  checkSEO: true
};

async function auditWebsite(url, options) {
  var startTime = Date.now();
  if (!UrlParser.isValid(url)) {
    return {
            TAG: "Error",
            _0: "Invalid URL: " + url
          };
  }
  try {
    var response = await Fetcher.fetchWithRetry(url, options.config, 0);
    if (response.TAG === "Ok") {
      var response$1 = response._0;
      if (!Fetcher.isHtmlContent(response$1)) {
        return {
                TAG: "Error",
                _0: "URL does not return HTML content"
              };
      }
      var html = response$1.body;
      var linkCheckPromise;
      if (options.checkLinks) {
        var links = UrlParser.extractLinks(html, url);
        linkCheckPromise = LinkChecker.checkLinks(links, url, options.config).then(function (result) {
              return result;
            });
      } else {
        linkCheckPromise = Promise.resolve(undefined);
      }
      var accessibilityPromise = options.checkAccessibility && options.config.checkAccessibility ? Accessibility.check(html, url).then(function (result) {
              return result;
            }) : Promise.resolve(undefined);
      var performancePromise = options.checkPerformance && options.config.checkPerformance ? $$Performance.analyze(html, url).then(function (result) {
              return result;
            }) : Promise.resolve(undefined);
      var seoPromise = options.checkSEO && options.config.checkSEO ? SEO.analyze(html, url).then(function (result) {
              return result;
            }) : Promise.resolve(undefined);
      var match = await Promise.all([
            linkCheckPromise,
            accessibilityPromise,
            performancePromise,
            seoPromise
          ]);
      var endTime = Date.now();
      var executionTime = endTime - startTime;
      var report = Report.create(url, match[0], match[1], match[2], match[3], executionTime);
      return {
              TAG: "Ok",
              _0: report
            };
    }
    var err = response._0;
    var errorMsg;
    if (typeof err !== "object") {
      errorMsg = "Request timeout";
    } else {
      switch (err.TAG) {
        case "NetworkError" :
            errorMsg = "Network error: " + err._0;
            break;
        case "InvalidUrl" :
            errorMsg = "Invalid URL: " + err._0;
            break;
        case "HttpError" :
            errorMsg = "HTTP " + err._0.toString() + ": " + err._1;
            break;
        
      }
    }
    return {
            TAG: "Error",
            _0: errorMsg
          };
  }
  catch (raw_obj){
    var obj = Caml_js_exceptions.internalToOCamlException(raw_obj);
    if (obj.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: "Unexpected error: " + Core__Option.getOr(obj._1.message, "Unknown error")
            };
    } else {
      return {
              TAG: "Error",
              _0: "Unexpected error: Unknown"
            };
    }
  }
}

async function auditMultiple(urls, options) {
  var results = [];
  for(var i = 0 ,i_finish = urls.length; i < i_finish; ++i){
    var url = urls[i];
    if (url !== undefined) {
      if (options.config.verbose) {
        console.log("Auditing " + (i + 1 | 0).toString() + "/" + urls.length.toString() + ": " + url);
      }
      var result = await auditWebsite(url, options);
      results.push(result);
    }
    if (i < (urls.length - 1 | 0)) {
      await new Promise((function (resolve, _reject) {
              setTimeout((function () {
                      resolve();
                    }), 500);
            }));
    }
    
  }
  return results;
}

function makeOptions(configOpt, checkLinksOpt, checkAccessibilityOpt, checkPerformanceOpt, checkSEOOpt, param) {
  var config = configOpt !== undefined ? configOpt : Config.default;
  var checkLinks = checkLinksOpt !== undefined ? checkLinksOpt : true;
  var checkAccessibility = checkAccessibilityOpt !== undefined ? checkAccessibilityOpt : true;
  var checkPerformance = checkPerformanceOpt !== undefined ? checkPerformanceOpt : true;
  var checkSEO = checkSEOOpt !== undefined ? checkSEOOpt : true;
  return {
          config: config,
          checkLinks: checkLinks,
          checkAccessibility: checkAccessibility,
          checkPerformance: checkPerformance,
          checkSEO: checkSEO
        };
}

async function printReport(report, format) {
  var formatted = await Report.format(report, format);
  console.log(formatted);
}

async function printResults(results, format) {
  for(var i = 0 ,i_finish = results.length; i < i_finish; ++i){
    var result = results[i];
    if (result !== undefined) {
      if (result.TAG === "Ok") {
        await printReport(result._0, format);
      } else {
        console.error("Error: " + result._0);
      }
      if (i < (results.length - 1 | 0)) {
        console.log("\n" + "=".repeat(80) + "\n");
      }
      
    }
    
  }
}

export {
  defaultOptions ,
  auditWebsite ,
  auditMultiple ,
  makeOptions ,
  printReport ,
  printResults ,
}
/* SEO Not a pure module */
