// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.js";

function make(maxDepth, followExternal, timeout, userAgent, checkAccessibility, checkPerformance, checkSEO, reportFormat, verbose, maxConcurrency, retryAttempts, retryDelay, param) {
  return {
          maxDepth: Core__Option.getOr(maxDepth, 3),
          followExternal: Core__Option.getOr(followExternal, false),
          timeout: Core__Option.getOr(timeout, 30000),
          userAgent: Core__Option.getOr(userAgent, "BroadSpectrum-Auditor/1.0"),
          checkAccessibility: Core__Option.getOr(checkAccessibility, true),
          checkPerformance: Core__Option.getOr(checkPerformance, true),
          checkSEO: Core__Option.getOr(checkSEO, true),
          reportFormat: Core__Option.getOr(reportFormat, "Console"),
          verbose: Core__Option.getOr(verbose, false),
          maxConcurrency: Core__Option.getOr(maxConcurrency, 10),
          retryAttempts: Core__Option.getOr(retryAttempts, 3),
          retryDelay: Core__Option.getOr(retryDelay, 1000)
        };
}

function formatToString(format) {
  switch (format) {
    case "Console" :
        return "console";
    case "JSON" :
        return "json";
    case "HTML" :
        return "html";
    case "Markdown" :
        return "markdown";
    
  }
}

function formatFromString(str) {
  var match = str.toLowerCase();
  switch (match) {
    case "console" :
        return "Console";
    case "html" :
        return "HTML";
    case "json" :
        return "JSON";
    case "markdown" :
    case "md" :
        return "Markdown";
    default:
      return ;
  }
}

var $$default = {
  maxDepth: 3,
  followExternal: false,
  timeout: 30000,
  userAgent: "BroadSpectrum-Auditor/1.0",
  checkAccessibility: true,
  checkPerformance: true,
  checkSEO: true,
  reportFormat: "Console",
  verbose: false,
  maxConcurrency: 10,
  retryAttempts: 3,
  retryDelay: 1000
};

export {
  $$default as default,
  make ,
  formatToString ,
  formatFromString ,
}
/* No side effect */
