// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FetcherTs from "./bindings/fetcher.ts";

function fetchUrl(prim0, prim1, prim2, prim3) {
  return FetcherTs.fetchUrl(prim0, prim1, prim2, prim3);
}

function fetchHead(prim0, prim1, prim2) {
  return FetcherTs.fetchHead(prim0, prim1, prim2);
}

async function $$fetch(url, config) {
  return await fetchUrl(url, config.timeout, config.userAgent, "GET");
}

async function fetchWithMethod(url, method, config) {
  var methodStr;
  switch (method) {
    case "GET" :
        methodStr = "GET";
        break;
    case "POST" :
        methodStr = "POST";
        break;
    case "HEAD" :
        methodStr = "HEAD";
        break;
    
  }
  if (method === "HEAD") {
    return await FetcherTs.fetchHead(url, config.timeout, config.userAgent);
  } else {
    return await fetchUrl(url, config.timeout, config.userAgent, methodStr);
  }
}

async function fetchWithRetry(url, config, attempt) {
  var result = await $$fetch(url, config);
  if (result.TAG === "Ok") {
    return result;
  }
  if (attempt >= config.retryAttempts) {
    return result;
  }
  var delay = Math.imul(config.retryDelay, attempt + 1 | 0);
  await new Promise((function (resolve, _reject) {
          setTimeout((function () {
                  resolve();
                }), delay);
        }));
  return await fetchWithRetry(url, config, attempt + 1 | 0);
}

function isSuccessStatus(status) {
  if (status >= 200) {
    return status < 300;
  } else {
    return false;
  }
}

function isRedirectStatus(status) {
  if (status >= 300) {
    return status < 400;
  } else {
    return false;
  }
}

function isClientErrorStatus(status) {
  if (status >= 400) {
    return status < 500;
  } else {
    return false;
  }
}

function isServerErrorStatus(status) {
  if (status >= 500) {
    return status < 600;
  } else {
    return false;
  }
}

function getContentType(response) {
  return response.headers["content-type"];
}

function isHtmlContent(response) {
  var contentType = response.headers["content-type"];
  if (contentType !== undefined) {
    return contentType.includes("text/html");
  } else {
    return false;
  }
}

export {
  fetchUrl ,
  fetchHead ,
  $$fetch ,
  fetchWithMethod ,
  fetchWithRetry ,
  isSuccessStatus ,
  isRedirectStatus ,
  isClientErrorStatus ,
  isServerErrorStatus ,
  getContentType ,
  isHtmlContent ,
}
/* ./bindings/fetcher.ts Not a pure module */
