// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fetcher from "./Fetcher.js";
import * as UrlParser from "./UrlParser.js";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as Core__Array from "@rescript/core/src/Core__Array.js";

async function checkLink(url, baseUrl, config) {
  var isExternal = !UrlParser.isSameDomain(url, baseUrl);
  if (isExternal && !config.followExternal) {
    return {
            url: url,
            status: 0,
            statusText: "Skipped (external)",
            external: isExternal,
            broken: false,
            redirectUrl: undefined,
            responseTime: 0.0,
            errorMessage: undefined
          };
  }
  var startTime = Date.now();
  var result = await Fetcher.fetchWithRetry(url, config, 0);
  var endTime = Date.now();
  var responseTime = endTime - startTime;
  if (result.TAG === "Ok") {
    var response = result._0;
    var broken = !Fetcher.isSuccessStatus(response.status);
    var redirectUrl = response.redirected ? response.finalUrl : undefined;
    return {
            url: url,
            status: response.status,
            statusText: response.statusText,
            external: isExternal,
            broken: broken,
            redirectUrl: redirectUrl,
            responseTime: responseTime,
            errorMessage: broken ? "HTTP " + response.status.toString() : undefined
          };
  }
  var err = result._0;
  var errorMsg;
  if (typeof err !== "object") {
    errorMsg = "Request timeout";
  } else {
    switch (err.TAG) {
      case "NetworkError" :
          errorMsg = err._0;
          break;
      case "InvalidUrl" :
          errorMsg = "Invalid URL: " + err._0;
          break;
      case "HttpError" :
          errorMsg = "HTTP " + err._0.toString() + ": " + err._1;
          break;
      
    }
  }
  return {
          url: url,
          status: 0,
          statusText: "Error",
          external: isExternal,
          broken: true,
          redirectUrl: undefined,
          responseTime: responseTime,
          errorMessage: errorMsg
        };
}

async function checkLinks(urls, baseUrl, config) {
  var seen = {};
  var unique = [];
  urls.forEach(function (url) {
        var match = seen[url];
        if (match !== undefined) {
          return ;
        } else {
          unique.push(url);
          seen[url] = true;
          return ;
        }
      });
  var batchSize = config.maxConcurrency;
  var results = [];
  for(var i = 0 ,i_finish = Caml_int32.div(unique.length - 1 | 0, batchSize); i <= i_finish; ++i){
    var start = Math.imul(i, batchSize);
    var endCalc = Math.imul(i + 1 | 0, batchSize);
    var end = endCalc < unique.length ? endCalc : unique.length;
    var batch = unique.slice(start, end);
    var batchResults = await Promise.all(batch.map(function (url) {
              return checkLink(url, baseUrl, config);
            }));
    batchResults.forEach(function (result) {
          results.push(result);
        });
  }
  var brokenCount = Core__Array.reduce(results, 0, (function (acc, link) {
          if (link.broken) {
            return acc + 1 | 0;
          } else {
            return acc;
          }
        }));
  var externalCount = Core__Array.reduce(results, 0, (function (acc, link) {
          if (link.external) {
            return acc + 1 | 0;
          } else {
            return acc;
          }
        }));
  var redirectCount = Core__Array.reduce(results, 0, (function (acc, link) {
          var match = link.redirectUrl;
          if (match !== undefined) {
            return acc + 1 | 0;
          } else {
            return acc;
          }
        }));
  var totalResponseTime = Core__Array.reduce(results, 0.0, (function (acc, link) {
          return acc + link.responseTime;
        }));
  var avgResponseTime = results.length > 0 ? totalResponseTime / results.length : 0.0;
  return {
          checkedLinks: results,
          totalLinks: unique.length,
          brokenLinks: brokenCount,
          externalLinks: externalCount,
          redirects: redirectCount,
          averageResponseTime: avgResponseTime
        };
}

export {
  checkLink ,
  checkLinks ,
}
/* Fetcher Not a pure module */
