// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.js";
import * as HtmlParserTs from "./bindings/htmlParser.ts";

function analyzePerformance(prim0, prim1) {
  return HtmlParserTs.analyzePerformance(prim0, prim1);
}

async function analyze(html, url) {
  var metrics = await HtmlParserTs.analyzePerformance(html, url);
  var suggestions = [];
  var warnings = [];
  if (metrics.totalPageSize > 3000000) {
    suggestions.push("Page size exceeds 3MB. Consider optimizing images and assets.");
  }
  if (metrics.resourceCount > 100) {
    suggestions.push("High number of resources (" + metrics.resourceCount.toString() + "). Consider bundling assets.");
  }
  var lcp = metrics.largestContentfulPaint;
  if (lcp !== undefined && lcp > 2500.0) {
    warnings.push("LCP is " + lcp.toString() + "ms (should be < 2.5s). Optimize largest content elements.");
  }
  var fcp = metrics.firstContentfulPaint;
  if (fcp !== undefined && fcp > 1800.0) {
    warnings.push("FCP is " + fcp.toString() + "ms (should be < 1.8s). Improve initial render time.");
  }
  var cls = metrics.cumulativeLayoutShift;
  if (cls !== undefined && cls > 0.1) {
    warnings.push("CLS is " + cls.toString() + " (should be < 0.1). Reduce layout shifts.");
  }
  var blockingScripts = metrics.resources.filter(function (r) {
        if (r.resourceType === "script" && !r.url.includes("async")) {
          return !r.url.includes("defer");
        } else {
          return false;
        }
      }).length;
  if (blockingScripts > 0) {
    suggestions.push(blockingScripts.toString() + " blocking scripts found. Use async/defer attributes.");
  }
  return {
          metrics: metrics,
          suggestions: suggestions,
          warnings: warnings
        };
}

function calculateScore(metrics) {
  var score = 100.0;
  if (metrics.loadComplete > 3000.0) {
    score = score - 20.0;
  } else if (metrics.loadComplete > 2000.0) {
    score = score - 10.0;
  } else if (metrics.loadComplete > 1000.0) {
    score = score - 5.0;
  }
  if (metrics.totalPageSize > 5000000) {
    score = score - 20.0;
  } else if (metrics.totalPageSize > 3000000) {
    score = score - 10.0;
  } else if (metrics.totalPageSize > 1000000) {
    score = score - 5.0;
  }
  var lcp = metrics.largestContentfulPaint;
  if (lcp !== undefined) {
    if (lcp > 4000.0) {
      score = score - 20.0;
    } else if (lcp > 2500.0) {
      score = score - 10.0;
    }
    
  }
  var cls = metrics.cumulativeLayoutShift;
  if (cls !== undefined) {
    if (cls > 0.25) {
      score = score - 15.0;
    } else if (cls > 0.1) {
      score = score - 7.0;
    }
    
  }
  if (score < 0.0) {
    return 0.0;
  } else {
    return score;
  }
}

function getResourcesByType(metrics) {
  var grouped = {};
  metrics.resources.forEach(function (resource) {
        var existing = Core__Option.getOr(grouped[resource.resourceType], []);
        existing.push(resource);
        grouped[resource.resourceType] = existing;
      });
  return grouped;
}

function getTotalSizeByType(metrics) {
  var sizes = {};
  metrics.resources.forEach(function (resource) {
        var existing = Core__Option.getOr(sizes[resource.resourceType], 0);
        sizes[resource.resourceType] = existing + resource.size | 0;
      });
  return sizes;
}

function formatBytes(bytes) {
  var kb = bytes / 1024.0;
  var mb = kb / 1024.0;
  if (mb >= 1.0) {
    return mb.toFixed(2) + "MB";
  } else if (kb >= 1.0) {
    return kb.toFixed(2) + "KB";
  } else {
    return bytes.toString() + "B";
  }
}

export {
  analyzePerformance ,
  analyze ,
  calculateScore ,
  getResourcesByType ,
  getTotalSizeByType ,
  formatBytes ,
}
/* ./bindings/htmlParser.ts Not a pure module */
