// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SEO from "./SEO.js";
import * as $$Performance from "./Performance.js";
import * as Core__Option from "@rescript/core/src/Core__Option.js";
import * as Accessibility from "./Accessibility.js";
import * as ReportTs from "./bindings/report.ts";

function formatAsJSON(prim) {
  return ReportTs.formatAsJSON(prim);
}

function formatAsHTML(prim) {
  return ReportTs.formatAsHTML(prim);
}

function formatAsMarkdown(prim) {
  return ReportTs.formatAsMarkdown(prim);
}

function calculateOverallScore(linkCheck, accessibility, performance, seo) {
  var totalScore = 0.0;
  var totalWeight = 0.0;
  if (linkCheck !== undefined) {
    var brokenPercent = linkCheck.totalLinks > 0 ? linkCheck.brokenLinks / linkCheck.totalLinks * 100.0 : 0.0;
    var linkScore = 100.0 - brokenPercent;
    totalScore = totalScore + linkScore * 0.2;
    totalWeight = totalWeight + 0.2;
  }
  if (accessibility !== undefined) {
    totalScore = totalScore + accessibility.score * 0.3;
    totalWeight = totalWeight + 0.3;
  }
  if (performance !== undefined) {
    var perfScore = $$Performance.calculateScore(performance.metrics);
    totalScore = totalScore + perfScore * 0.3;
    totalWeight = totalWeight + 0.3;
  }
  if (seo !== undefined) {
    totalScore = totalScore + seo.score * 0.2;
    totalWeight = totalWeight + 0.2;
  }
  if (totalWeight > 0.0) {
    return totalScore / totalWeight;
  } else {
    return 0.0;
  }
}

function create(url, linkCheck, accessibility, performance, seo, executionTime) {
  var overallScore = calculateOverallScore(linkCheck, accessibility, performance, seo);
  return {
          url: url,
          timestamp: Date.now().toString(),
          linkCheck: linkCheck,
          accessibility: accessibility,
          performance: performance,
          seo: seo,
          overallScore: overallScore,
          executionTime: executionTime
        };
}

function formatConsole(report) {
  var lines = [];
  lines.push("\n" + "=".repeat(80));
  lines.push("WEBSITE AUDIT REPORT");
  lines.push("=".repeat(80));
  lines.push("URL: " + report.url);
  lines.push("Timestamp: " + report.timestamp);
  lines.push("Execution Time: " + (report.executionTime / 1000.0).toFixed(2) + "s");
  lines.push("Overall Score: " + report.overallScore.toFixed(1) + "/100");
  lines.push("=".repeat(80) + "\n");
  var result = report.linkCheck;
  if (result !== undefined) {
    lines.push("LINK CHECK");
    lines.push("-".repeat(80));
    lines.push("Total Links: " + result.totalLinks.toString());
    lines.push("Broken Links: " + result.brokenLinks.toString());
    lines.push("External Links: " + result.externalLinks.toString());
    lines.push("Redirects: " + result.redirects.toString());
    lines.push("Average Response Time: " + result.averageResponseTime.toFixed(0) + "ms");
    if (result.brokenLinks > 0) {
      lines.push("\nBroken Links:");
      result.checkedLinks.filter(function (link) {
              return link.broken;
            }).forEach(function (link) {
            var error = Core__Option.getOr(link.errorMessage, "Unknown error");
            lines.push("  - " + link.url + " [" + error + "]");
          });
    }
    lines.push("");
  }
  var result$1 = report.accessibility;
  if (result$1 !== undefined) {
    lines.push("ACCESSIBILITY (WCAG " + Accessibility.levelToString(result$1.wcagLevel) + ")");
    lines.push("-".repeat(80));
    lines.push("Score: " + result$1.score.toFixed(1) + "/100");
    lines.push("Violations: " + result$1.violations.length.toString());
    lines.push("Warnings: " + result$1.warnings.length.toString());
    lines.push("Passes: " + result$1.passes.toString());
    if (result$1.violations.length > 0) {
      lines.push("\nTop Violations:");
      result$1.violations.slice(0, 5).forEach(function (violation) {
            lines.push("  - [" + violation.impact + "] " + violation.rule + ": " + violation.message);
          });
    }
    lines.push("");
  }
  var result$2 = report.performance;
  if (result$2 !== undefined) {
    var score = $$Performance.calculateScore(result$2.metrics);
    lines.push("PERFORMANCE");
    lines.push("-".repeat(80));
    lines.push("Score: " + score.toFixed(1) + "/100");
    lines.push("Page Size: " + $$Performance.formatBytes(result$2.metrics.totalPageSize));
    lines.push("Resources: " + result$2.metrics.resourceCount.toString());
    lines.push("Load Time: " + result$2.metrics.loadComplete.toFixed(0) + "ms");
    var lcp = result$2.metrics.largestContentfulPaint;
    if (lcp !== undefined) {
      lines.push("LCP: " + lcp.toFixed(0) + "ms");
    }
    var fcp = result$2.metrics.firstContentfulPaint;
    if (fcp !== undefined) {
      lines.push("FCP: " + fcp.toFixed(0) + "ms");
    }
    if (result$2.warnings.length > 0) {
      lines.push("\nWarnings:");
      result$2.warnings.forEach(function (warning) {
            lines.push("  - " + warning);
          });
    }
    lines.push("");
  }
  var result$3 = report.seo;
  if (result$3 !== undefined) {
    lines.push("SEO");
    lines.push("-".repeat(80));
    lines.push("Score: " + result$3.score.toFixed(1) + "/100");
    var title = result$3.data.title;
    if (title !== undefined) {
      lines.push("Title: " + title);
    } else {
      lines.push("Title: (missing)");
    }
    var desc = result$3.data.description;
    if (desc !== undefined) {
      var truncated = desc.length > 100 ? desc.substring(0, 100) + "..." : desc;
      lines.push("Description: " + truncated);
    } else {
      lines.push("Description: (missing)");
    }
    lines.push("Word Count: " + result$3.data.wordCount.toString());
    var errorCount = SEO.filterIssuesBySeverity(result$3.issues, "error").length;
    var warningCount = SEO.filterIssuesBySeverity(result$3.issues, "warning").length;
    if (errorCount > 0 || warningCount > 0) {
      lines.push("Issues: " + errorCount.toString() + " errors, " + warningCount.toString() + " warnings");
    }
    if (errorCount > 0) {
      lines.push("\nCritical Issues:");
      result$3.issues.filter(function (issue) {
              return issue.severity === "error";
            }).forEach(function (issue) {
            lines.push("  - " + issue.message);
          });
    }
    lines.push("");
  }
  lines.push("=".repeat(80));
  return lines.join("\n");
}

async function format(report, format$1) {
  switch (format$1) {
    case "Console" :
        return formatConsole(report);
    case "JSON" :
        return ReportTs.formatAsJSON(report);
    case "HTML" :
        return await ReportTs.formatAsHTML(report);
    case "Markdown" :
        return ReportTs.formatAsMarkdown(report);
    
  }
}

export {
  formatAsJSON ,
  formatAsHTML ,
  formatAsMarkdown ,
  calculateOverallScore ,
  create ,
  formatConsole ,
  format ,
}
/* SEO Not a pure module */
