// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.js";
import * as SeoParserTs from "./bindings/seoParser.ts";

function analyzeSEO(prim0, prim1) {
  return SeoParserTs.analyzeSEO(prim0, prim1);
}

function calculateScore(data, issues) {
  var score = {
    contents: 100.0
  };
  issues.forEach(function (issue) {
        var match = issue.severity;
        switch (match) {
          case "error" :
              score.contents = score.contents - 10.0;
              return ;
          case "info" :
              score.contents = score.contents - 2.0;
              return ;
          case "warning" :
              score.contents = score.contents - 5.0;
              return ;
          default:
            return ;
        }
      });
  if (data.structuredData) {
    score.contents = score.contents + 5.0;
  }
  if (Object.entries(data.ogTags).length > 0) {
    score.contents = score.contents + 3.0;
  }
  if (data.wordCount > 1000) {
    score.contents = score.contents + 5.0;
  }
  var finalScore = score.contents;
  if (finalScore < 0.0) {
    return 0.0;
  } else if (finalScore > 100.0) {
    return 100.0;
  } else {
    return finalScore;
  }
}

async function analyze(html, url) {
  var data = await SeoParserTs.analyzeSEO(html, url);
  var issues = [];
  var title = data.title;
  if (title !== undefined) {
    var titleLength = title.length;
    if (titleLength < 30) {
      issues.push({
            severity: "warning",
            message: "Title is too short (" + titleLength.toString() + " chars). Recommended: 30-60 characters.",
            element: "<title>" + title + "</title>"
          });
    } else if (titleLength > 60) {
      issues.push({
            severity: "warning",
            message: "Title is too long (" + titleLength.toString() + " chars). Recommended: 30-60 characters.",
            element: "<title>" + title + "</title>"
          });
    }
    
  } else {
    issues.push({
          severity: "error",
          message: "Missing page title (<title> tag)",
          element: undefined
        });
  }
  var desc = data.description;
  if (desc !== undefined) {
    var descLength = desc.length;
    if (descLength < 120) {
      issues.push({
            severity: "warning",
            message: "Meta description is too short (" + descLength.toString() + " chars). Recommended: 120-160 characters.",
            element: "<meta name=\"description\" content=\"" + desc + "\">"
          });
    } else if (descLength > 160) {
      issues.push({
            severity: "info",
            message: "Meta description is too long (" + descLength.toString() + " chars). May be truncated in search results.",
            element: "<meta name=\"description\" content=\"" + desc + "\">"
          });
    }
    
  } else {
    issues.push({
          severity: "error",
          message: "Missing meta description",
          element: undefined
        });
  }
  var h1Count = Core__Option.getOr(Core__Option.map(data.headings["h1"], (function (prim) {
              return prim.length;
            })), 0);
  if (h1Count === 0) {
    issues.push({
          severity: "error",
          message: "Missing H1 heading",
          element: undefined
        });
  } else if (h1Count > 1) {
    issues.push({
          severity: "warning",
          message: "Multiple H1 headings found (" + h1Count.toString() + "). Use only one H1 per page.",
          element: undefined
        });
  }
  if (data.images > 0) {
    var percentWithAlt = data.imagesWithAlt / data.images * 100.0;
    if (percentWithAlt < 100.0) {
      var missing = data.images - data.imagesWithAlt | 0;
      issues.push({
            severity: "warning",
            message: missing.toString() + " images missing alt text (" + percentWithAlt.toFixed(1) + "% have alt text)",
            element: undefined
          });
    }
    
  }
  var match = data.canonical;
  if (match !== undefined) {
    
  } else {
    issues.push({
          severity: "info",
          message: "No canonical URL specified",
          element: undefined
        });
  }
  if (Object.entries(data.ogTags).length === 0) {
    issues.push({
          severity: "info",
          message: "No Open Graph tags found. Add OG tags for better social media sharing.",
          element: undefined
        });
  }
  if (!data.structuredData) {
    issues.push({
          severity: "info",
          message: "No structured data (JSON-LD) found. Consider adding schema.org markup.",
          element: undefined
        });
  }
  var match$1 = data.viewport;
  if (match$1 !== undefined) {
    
  } else {
    issues.push({
          severity: "warning",
          message: "Missing viewport meta tag for mobile responsiveness",
          element: undefined
        });
  }
  var match$2 = data.lang;
  if (match$2 !== undefined) {
    
  } else {
    issues.push({
          severity: "warning",
          message: "Missing lang attribute on <html> tag",
          element: undefined
        });
  }
  if (data.wordCount < 300) {
    issues.push({
          severity: "warning",
          message: "Low word count (" + data.wordCount.toString() + " words). Pages with more content tend to rank better.",
          element: undefined
        });
  }
  var score = calculateScore(data, issues);
  return {
          data: data,
          issues: issues,
          score: score
        };
}

function filterIssuesBySeverity(issues, severity) {
  return issues.filter(function (issue) {
              return issue.severity === severity;
            });
}

function getIssueCount(issues) {
  var counts = {};
  counts["error"] = 0;
  counts["warning"] = 0;
  counts["info"] = 0;
  issues.forEach(function (issue) {
        var current = Core__Option.getOr(counts[issue.severity], 0);
        counts[issue.severity] = current + 1 | 0;
      });
  return counts;
}

export {
  analyzeSEO ,
  calculateScore ,
  analyze ,
  filterIssuesBySeverity ,
  getIssueCount ,
}
/* ./bindings/seoParser.ts Not a pure module */
