// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AdaTs from "./bindings/ada.ts";
import * as HtmlParserTs from "./bindings/htmlParser.ts";

function parseUrl(prim) {
  return AdaTs.parseUrl(prim);
}

function isValidUrl(prim) {
  return AdaTs.isValidUrl(prim);
}

function normalizeUrl(prim) {
  return AdaTs.normalizeUrl(prim);
}

function parse(url) {
  return AdaTs.parseUrl(url);
}

function isValid(url) {
  return AdaTs.isValidUrl(url);
}

function normalize(url) {
  return AdaTs.normalizeUrl(url);
}

function getUrlType(url, baseUrl) {
  var parsed = AdaTs.parseUrl(url);
  if (parsed === undefined) {
    return "Invalid";
  }
  var baseParsed = AdaTs.parseUrl(baseUrl);
  if (baseParsed !== undefined) {
    if (parsed.hostname === baseParsed.hostname) {
      return "Internal";
    } else if (parsed.protocol === "http:" || parsed.protocol === "https:") {
      return "External";
    } else {
      return "Invalid";
    }
  } else {
    return "Invalid";
  }
}

function makeAbsolute(url, baseUrl) {
  if (url.startsWith("http://") || url.startsWith("https://")) {
    return url;
  }
  var base = AdaTs.parseUrl(baseUrl);
  if (base === undefined) {
    return ;
  }
  var tmp;
  if (url.startsWith("/")) {
    tmp = base.origin + url;
  } else if (url.startsWith("#")) {
    tmp = base.origin + base.pathname + url;
  } else if (url.startsWith("?")) {
    tmp = base.origin + base.pathname + url;
  } else {
    var basePath = base.pathname;
    var lastSlash = basePath.lastIndexOf("/");
    var dir = basePath.substring(0, lastSlash + 1 | 0);
    tmp = base.origin + dir + url;
  }
  return tmp;
}

function isSameDomain(url1, url2) {
  var match = AdaTs.parseUrl(url1);
  var match$1 = AdaTs.parseUrl(url2);
  if (match !== undefined && match$1 !== undefined) {
    return match.hostname === match$1.hostname;
  } else {
    return false;
  }
}

function extractLinksFromHtml(prim0, prim1) {
  return HtmlParserTs.extractLinksFromHtml(prim0, prim1);
}

function extractLinks(html, baseUrl) {
  return HtmlParserTs.extractLinksFromHtml(html, baseUrl);
}

export {
  parseUrl ,
  isValidUrl ,
  normalizeUrl ,
  parse ,
  isValid ,
  normalize ,
  getUrlType ,
  makeAbsolute ,
  isSameDomain ,
  extractLinksFromHtml ,
  extractLinks ,
}
/* ./bindings/ada.ts Not a pure module */
